### ISSUE TITLE
CentOS Linux release 7.7.1908 运行报错

### ISSUE THREAD

**Issue by y377** [Ericwyn/Andex#2]
你好，首先感谢开源！
请问我下载的Linux 64直接运行报错，我大概查了一下百度，说要安装gcc，g++，确认已安装且并未解决；报错详情如下：
```
[root@node1 ~]# ./Andex

 ______     __   __     _____     ______     __  __
/\  __ \   /\ "-.\ \   /\  __-.  /\  ___\   /\_\_\_\
\ \  __ \  \ \ \-.  \  \ \ \/\ \ \ \  __\   \/_/\_\/_
 \ \_\ \_\  \ \_\\"\_\  \ \____-  \ \_____\   /\_\/\_\
  \/_/\/_/   \/_/ \/_/   \/____/   \/_____/   \/_/\/_/

Welcome to use Andex Version V1.2
Release in https://github.com/Ericwyn/Andex

Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
[Andex-ERR ] [0712-105737] SYNC TABLE ERROR!!
[root@node1 ~]#
```

**Comment by Ericwyn** [comment]
Hi～
二进制程序我是在 windows 上面使用交叉编译得到的，因此编译得到的 go-sqlite3 依赖可能会有问题
你可以 clone 源码之后，在 linux 环境下再编译以便

clone 了源码之后，进入源码目录
使用 `go build Andex.go` 就可以了～

编译生成的二进制文件为 源码目录下 `Andex`，你可以直接使用 `./Andex` 命令来运行

**Comment by y377** [comment]
你好，还是有问题！
我是下载的你发布的[源码](https://github.com/Ericwyn/Andex/releases/tag/V1.2）（V1.2.tar.gz），我在Linux机器下，

然后运行`go build Andex.go`;
运行完了以后当前路劲下多了一个**### Andex**：
```
[root@localhost Andex-1.2]# ls
ajax  Andex  Andex.go  api  build.bat  controller  go.mod  go.sum  modal  README.md  service  static  storage  util
[root@localhost Andex-1.2]#
```
当我运行`./Andex`时，报错如下：
```
[root@node1 ~]# ./Andex

 ______     __   __     _____     ______     __  __
/\  __ \   /\ "-.\ \   /\  __-.  /\  ___\   /\_\_\_\
\ \  __ \  \ \ \-.  \  \ \ \/\ \ \ \  __\   \/_/\_\/_
 \ \_\ \_\  \ \_\\"\_\  \ \____-  \ \_____\   /\_\/\_\
  \/_/\/_/   \/_/ \/_/   \/____/   \/_____/   \/_/\/_/

Welcome to use Andex Version V1.2
Release in https://github.com/Ericwyn/Andex

unable to open database file: no such file or directory
[Andex-ERR ] [0713-122100] SYNC TABLE ERROR!!

```

**Comment by Ericwyn** [comment]
> Welcome to use Andex Version V1.2
> Release in https://github.com/Ericwyn/Andex
> 
> unable to open database file: no such file or directory
> [Andex-ERR ] [0713-122100] SYNC TABLE ERROR!!


感谢反馈，这个确实是我没写清楚
另外？这居然还有群？

**Comment by y377** [comment]
> > Welcome to use Andex Version V1.2
> > Release in https://github.com/Ericwyn/Andex
> > unable to open database file: no such file or directory
> > [Andex-ERR ] [0713-122100] SYNC TABLE ERROR!!
> 
> 感谢反馈，这个确实是我没写清楚
> 另外？这居然还有群？

嗯，没事！
是webdav的QQ群789738128
